Fail bbr restore if using an unsupported database
[#150242441] BBR restore should stop application before modifying database

Signed-off-by: Ben Moss <bmoss@pivotal.io>
Signed-off-by: Edie Beer <ebeer@pivotal.io>

diff --git a/jobs/credhub/templates/backup.erb b/jobs/credhub/templates/backup.erb
--- a/jobs/credhub/templates/backup.erb
+++ b/jobs/credhub/templates/backup.erb
@@ -56,5 +56,6 @@ export MYSQL_PWD="<%= dbpassword %>"
     <% end %>
 
 <% else %>
-echo "Skipping backup, as database is not Postgres or Mysql"
+echo "Cannot backup, as database is not Postgres or Mysql"
+exit 1
 <% end %>
diff --git a/jobs/credhub/templates/restore.erb b/jobs/credhub/templates/restore.erb
--- a/jobs/credhub/templates/restore.erb
+++ b/jobs/credhub/templates/restore.erb
@@ -57,5 +57,6 @@ if require_tls %>
 <% end %>
 
 <% else %>
-echo "Skipping restore, as database is not Postgres or MySql"
+echo "Cannot restore, as database is not Postgres or MySql"
+exit 1
 <% end %>
