Create wrapper function for vtl luna binary that fails when an Error message is returned
[#156653812] configure_hsm script doesn't report errors correctly

Signed-off-by: Mark DeLillo <mdelillo@pivotal.io>

diff --git a/jobs/credhub/templates/configure_hsm.erb b/jobs/credhub/templates/configure_hsm.erb
--- a/jobs/credhub/templates/configure_hsm.erb
+++ b/jobs/credhub/templates/configure_hsm.erb
@@ -1,6 +1,14 @@
 #!/bin/bash
 
 set -eu
+vtl_exec(){
+  output=$(vtl $@)
+  if echo "$output" | grep -q '^Error:'; then
+    echo "$output" >&2
+    exit 1
+  fi
+  echo "$output"
+}
 
 <%
   hsm_provider = p('credhub.encryption.providers').find  { |provider| provider['type'] == "hsm" }
@@ -38,12 +46,12 @@ cp /var/vcap/packages/lunaclient/jsp/lib/libLunaAPI.so $JAVA_HOME/lib/ext/
 
 PATH=$PATH:/var/vcap/packages/lunaclient/bin
 
-if [ $(vtl haAdmin show | egrep -c 'HA Group Label:\s+<%= ha_group_label %>(\s|$)') -eq 0 ]; then
+if [ $(vtl_exec haAdmin show | egrep -c 'HA Group Label:\s+<%= ha_group_label %>(\s|$)') -eq 0 ]; then
   echo "HSM HA appears to be uninitialized. Performing HA HSM setup."
 
   echo "Creating new HSM HA group."
 
-  NEW_GROUP_OUTPUT=$(echo copy | vtl haAdmin newGroup -label "<%= ha_group_label %>" -serialNum <%= primary_serial_number %> -password <%= hsm_provider['partition_password'] %>)
+  NEW_GROUP_OUTPUT=$(echo copy | vtl_exec haAdmin newGroup -label "<%= ha_group_label %>" -serialNum <%= primary_serial_number %> -password <%= hsm_provider['partition_password'] %>)
   GROUPID=$(echo $NEW_GROUP_OUTPUT | grep -o -E 'HA Group Number: .*' | awk '{print $4}')
 
   echo "Adding members to HSM HA group."
@@ -51,13 +59,13 @@ if [ $(vtl haAdmin show | egrep -c 'HA Group Label:\s+<%= ha_group_label %>(\s|$
 <% hsm_servers.each do |hsm_server| %>
   echo "Adding server with partition serial number <%= hsm_server['partition_serial_number'] %> to HSM HA group."
 
-  echo copy | vtl haAdmin addMember -group $GROUPID -serialNum <%= hsm_server['partition_serial_number'] %> -password <%= hsm_provider['partition_password'] %>
+  echo copy | vtl_exec haAdmin addMember -group $GROUPID -serialNum <%= hsm_server['partition_serial_number'] %> -password <%= hsm_provider['partition_password'] %>
 <% end %>
 
   echo "Finished adding members to HSM HA group."
 
   echo "Synchronizing HSM HA group."
-  vtl haAdmin synchronize -group $GROUPID -password <%= hsm_provider['partition_password'] %>
+  vtl_exec haAdmin synchronize -group $GROUPID -password <%= hsm_provider['partition_password'] %>
 else
   echo "HSM HA appears to be initialized. Skipping HSM HA setup."
 fi
