grep process table for credhub PID to make pidfile
It would have been ideal to use the 'jps' utility to search for
CredentialManagerApp, but sadly, when starting CredHub via the jar
command, jps just shows 'jar' as the process name. That's not reliable
enough, so instead we grep the process table to find the right pid.

[#135577729] PID is incorrect in pid file

diff --git a/jobs/credhub/templates/ctl b/jobs/credhub/templates/ctl
--- a/jobs/credhub/templates/ctl
+++ b/jobs/credhub/templates/ctl
@@ -21,8 +21,6 @@ case $1 in
     mkdir -p $RUN_DIR $LOG_DIR
     chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $TMP_DIR
 
-    echo $$ > $PIDFILE
-
     cd /var/vcap/packages/credhub
     exec chpst -u $RUNAS:$RUNAS java \
         -Dspring.config.location=/var/vcap/jobs/credhub/config/application.properties \
@@ -30,6 +28,16 @@ case $1 in
         -Djava.security.egd=file:/dev/urandom \
         -Djava.io.tmpdir=$TMP_DIR \
         -ea -jar *.jar
+
+    CREDHUB_PID=$(ps aux | grep java | grep 'credhub.jar' | awk '{print $2}')
+
+    if [ "$CREDHUB_PID" != "" ]; then
+        echo $CREDHUB_PID > $PIDFILE
+    else
+        echo "CredHub server failed to start. Please see logs for details."
+        exit 1
+    fi
+
     ;;
 
   stop)
